name: test-ublue-template
description: Coral-ready Fedora image for Frigate and expressive automation
image-name: ghcr.io/eightbysix/test-ublue-template
signing: true

packages:
  # Coral runtime and bindings
  - libedgetpu1-std
  - python3-pycoral
  - libusb1

postprocess:
  - |
    # Add udev rules so Coral USB devices are accessible without root
    echo 'SUBSYSTEM=="usb", ATTR{idVendor}=="1a6e", MODE="0666", GROUP="plugdev"' \
      > /etc/udev/rules.d/99-edgetpu-accelerator.rules
