name: test-ublue-template
description: Coral-ready Fedora image for Frigate and expressive automation
image-name: ghcr.io/eightbysix/test-ublue-template
signing: true

packages:
  - libedgetpu1-std
  - python3-pycoral


# Add udev rules for Coral USB
postprocess:
  - |
    echo 'SUBSYSTEM=="usb", ATTR{idVendor}=="1a6e", MODE="0666", GROUP="plugdev"' \
      > /etc/udev/rules.d/99-edgetpu-accelerator.rules
